apiVersion: v1
kind: Secret
metadata:
  name: user-app-secret
  namespace: user-app
type: Opaque
stringData:
  MONGO_URI: mongodb://admin:password123@mongo:27017/mydb?authSource=admin
  JWT_SECRET: supersecretkey288
