apiVersion: v1
kind: Secret
metadata:
  name: user-app-secret
  namespace: user-app
type: Opaque
stringData:
  MONGO_USER: dummyuser
  MONGO_PASSWORD: dummypass
  MONGO_URI: mongodb://dummyuser:dummypass@mongo:27017/mydb?authSource=admin
  JWT_SECRET: dummyjwt
