apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-app-deployment
  namespace: user-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: user-app
    spec:
      securityContext:
        fsGroup: 2000
      initContainers:
      - image: busybox:latest
        name: check-mongo-dns
        env:
        - name: MONGO_SVC
          valueFrom:
            configMapKeyRef:
              name: user-app-config
              key: MONGO_SVC
        - name: MONGO_PORT
          valueFrom:
            configMapKeyRef:
              name: user-app-config
              key: MONGO_PORT
        command: ["/bin/sh", "-c", "until nc -z $MONGO_SVC $MONGO_PORT; do echo 'checking mongo db service port'; sleep 10; done"]
      containers:
      - image: iconickyle/user-app:c54f4f6734a4a16666089400ece0ec458f4eeed5
        name: user-app
        ports:
        - containerPort: 4000
        resources: {}
        securityContext:
          runAsUser: 1000
          runAsGroup: 3000
          runAsNonRoot: true
          capabilities:
            drop:
              - ALL
        envFrom:
        - configMapRef:
            name: user-app-config
        - secretRef:
            name: user-app-secret
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 4000
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health/live
            port: 4000
          initialDelaySeconds: 10
          periodSeconds: 10