apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-app-deployment
  namespace: user-app
spec:
  replicas: 2

  selector:
    matchLabels:
      app: user-app

  template:
    metadata:
      labels:
        app: user-app

    spec:
      containers:
        - name: user-app
          image: iconickyle/user-app:v1.0.0

          ports:
            - containerPort: 4000

          resources: {}
          securityContext: {}

          envFrom:
            - configMapRef:
                name: user-app-config

            - secretRef:
                name: user-app-secret

          readinessProbe:
            httpGet:
              path: /health/ready
              port: 4000
            initialDelaySeconds: 5
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /health/live
              port: 4000
            initialDelaySeconds: 10
            periodSeconds: 10
